# Generated by Django 4.0.3 on 2022-05-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_p_name_product_name_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='p_name',
        ),
    ]
