# Generated by Django 4.0.3 on 2022-05-17 10:07

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_cart_value',
            field=picklefield.fields.PickledObjectField(default=None, editable=False),
        ),
    ]
