# Generated by Django 4.0.3 on 2022-05-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_customer_user_cart_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_cart_value',
            new_name='user_cart_values',
        ),
    ]
