# Generated by Django 4.0.3 on 2022-05-17 10:08

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_rename_user_cart_value_customer_user_cart_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_cart_values',
        ),
        migrations.AddField(
            model_name='customer',
            name='users_cart_values',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
