# Generated by Django 4.0.3 on 2022-05-17 10:10

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_customer_user_cart_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users_cart_values',
        ),
        migrations.AddField(
            model_name='customer',
            name='users_cart',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
