# Generated by Django 4.0.3 on 2022-05-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_customer_users_cart_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users_cart',
        ),
    ]
