# Generated by Django 4.0.3 on 2022-07-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_customer_user_cart_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_cart_value',
        ),
    ]
