# Generated by Django 4.0.3 on 2022-07-15 15:35

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_customer_user_cart_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_cart_value',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
