# Generated by Django 4.0.3 on 2022-07-15 15:37

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_customer_user_cart_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_cart_value',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
